name: ActionCephAdmTest

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

defaults:
  run:
    # reference: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#using-a-specific-shell
    shell: bash --noprofile --norc -eo pipefail -x {0}

jobs:
  CephAdmTest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: prep local block device
        run:  ./scripts/cephadm-test.sh use_local_disk

      - name: deploy cluster with given image
        run:  ./scripts/cephadm-test.sh deploy_cephadm quay.io/ceph/ceph:v17

      - name: add osd
        run:  ./scripts/cephadm-test.sh add_osds

      - name: consider debugging
        uses: lhotari/action-upterm@v1
        if: failure()
