name: Publish Temporary ROCK

on: 
  issue_comment:
    types: [created]

jobs:
  pr_commented:
    name: PR comment
    # Run only if the comment is on a pull request and contains the keyword.
    if: ${{ github.event.issue.pull_request }} && contains(github.event.comment.body, '/publish') 
    runs-on: ubuntu-latest
    outputs:
      rock: ${{ steps.rockcraft.outputs.rock }}
    steps:
      - run: |
          echo Publishing container image for PR# $NUMBER
        env:
          NUMBER: ${{ github.event.issue.number }}

      # Get branch from PR as issue_comment references the main branch by default.
      - uses: xt0rted/pull-request-comment-branch@v2
        id: comment-branch

      - uses: actions/checkout@v3
        if: success()
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}

      - name: login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ghcr.io/canonical/ceph
          # Create OCI tag using the PR.
          tags: |
            type=ref,event=pr

      - name: Prepare Rock
        uses: canonical/craft-actions/rockcraft-pack@main
        id: rockcraft

      - name: Load to Docker daemon
        run: |
            skopeo --insecure-policy copy oci-archive:${{ steps.rockcraft.outputs.rock }} docker-daemon:${{ steps.meta.outputs.tags }}
            docker image ls -a
            sleep 10
            docker push ${{ steps.meta.outputs.tags }}

